### ISSUE TITLE
service layer

### ISSUE THREAD

**Issue by AlexanderTorchynskyi** [gustavoponce7/SpringBootRESTfulTutorial#2]
Can you explain why you need service layer that duplicates repository methods?

**Comment by gustavoponce7** [comment]
In this project the service and data layer look very similar because thanks to JPARepository the persistence operations happen out of the box, but imagine that you need to write the actual SQL, so you will have your data logic in the application logic (Service layer)

In conclusion --> The application logic should be implemented in service layer, and the data logic(CRUD) should be implemented in data layer

You can find more information here:
https://www.safaribooksonline.com/library/view/software-architecture-patterns/9781491971437/ch01.html
